version: "3.8"

services:
  db:
    image: "mariadb:latest"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_database:/var/lib/mysql/materials_browser
    networks:
      - "mbnet"
    ports:
      - "127.0.0.1:3306:3306"

  web:
    build:
      context: .
      args:
        - API_ADDRESS=${API_ADDRESS}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - SYMFONY_APP_ENV=${SYMFONY_APP_ENV}
        - SYMFONY_APP_DEBUG=${SYMFONY_APP_DEBUG}
    ports:
      - "80:80"
      - "443:443"
    links:
      - "db"
    networks:
      - "mbnet"
    depends_on:
      - "db"
    environment:
      HTTPD_SERVER_ALIAS: ${HTTPD_SERVER_ALIAS}
      HTTPD_SERVER_NAME: ${HTTPD_SERVER_NAME}
      HTTPD_SERVER_ADMIN: ${HTTPD_SERVER_ADMIN}

networks:
  mbnet: {}

volumes:
  mysql_data:
    external: true
  mysql_database:
    external: true
